// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsAS-p0m5JZo3cBckMVILG7xNiEDiObmU',
    appId: '1:1063768818189:web:0fb05b7fe560f96a560b44',
    messagingSenderId: '1063768818189',
    projectId: 'shift-tracker-f67ff',
    authDomain: 'shift-tracker-f67ff.firebaseapp.com',
    storageBucket: 'shift-tracker-f67ff.appspot.com',
    measurementId: 'G-FM29V55G4G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_96J91tlDxDpJboYOtMKRnMn5CIATgHQ',
    appId: '1:1063768818189:android:640d858790a487c7560b44',
    messagingSenderId: '1063768818189',
    projectId: 'shift-tracker-f67ff',
    storageBucket: 'shift-tracker-f67ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsGo40rgCa7_c9l_tP0IkCrIvF4rQ4OGU',
    appId: '1:1063768818189:ios:d2085080b564a893560b44',
    messagingSenderId: '1063768818189',
    projectId: 'shift-tracker-f67ff',
    storageBucket: 'shift-tracker-f67ff.appspot.com',
    iosClientId: '1063768818189-d2qjpks1o7uite2vnt1q4gpdk0dfig3j.apps.googleusercontent.com',
    iosBundleId: 'com.comits.shifts',
  );
}
